
# น่าจะเสร็จแล้ว ต้องเช็ก
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.00.tar.gz > output-00.txt 2>&1 &

# กำลังรันอยู่
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.01.tar.tz > output-01.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.02.tar.tz > output-02.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.03.tar.tz > output-03.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.04.tar.tz > output-04.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.05.tar.tz > output-05.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.06.tar.tz > output-06.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.07.tar.tz > output-07.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.08.tar.tz > output-08.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.09.tar.tz > output-09.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.10.tar.tz > output-10.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.11.tar.tz > output-11.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.12.tar.tz > output-12.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.13.tar.tz > output-13.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.14.tar.tz > output-14.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.15.tar.tz > output-15.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.16.tar.tz > output-16.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.17.tar.tz > output-17.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.18.tar.tz > output-18.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.19.tar.tz > output-19.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.20.tar.tz > output-20.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.21.tar.tz > output-21.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.22.tar.tz > output-22.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.23.tar.tz > output-23.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.24.tar.tz > output-24.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.25.tar.tz > output-25.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.26.tar.tz > output-26.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.27.tar.tz > output-27.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.28.tar.tz > output-28.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.29.tar.tz > output-29.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.30.tar.tz > output-30.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.31.tar.tz > output-31.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.32.tar.tz > output-32.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.33.tar.tz > output-33.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.34.tar.tz > output-34.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.35.tar.tz > output-35.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.36.tar.tz > output-36.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.37.tar.tz > output-37.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.38.tar.tz > output-38.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.39.tar.tz > output-39.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.40.tar.tz > output-40.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.41.tar.tz > output-41.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.42.tar.tz > output-42.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.43.tar.tz > output-43.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.44.tar.tz > output-44.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.45.tar.tz > output-45.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.46.tar.tz > output-46.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.47.tar.tz > output-47.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.48.tar.tz > output-48.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.49.tar.tz > output-49.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.50.tar.tz > output-50.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.51.tar.tz > output-51.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.52.tar.tz > output-52.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.53.tar.tz > output-53.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.54.tar.tz > output-54.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.55.tar.tz > output-55.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.56.tar.tz > output-56.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.57.tar.tz > output-57.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.58.tar.tz > output-58.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.59.tar.tz > output-59.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.60.tar.tz > output-60.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.61.tar.tz > output-61.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.62.tar.tz > output-62.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.63.tar.tz > output-63.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.64.tar.tz > output-64.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.65.tar.tz > output-65.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.66.tar.tz > output-66.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.67.tar.tz > output-67.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.68.tar.tz > output-68.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.69.tar.tz > output-69.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.70.tar.tz > output-70.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.71.tar.tz > output-71.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.72.tar.tz > output-72.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.73.tar.tz > output-73.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.74.tar.tz > output-74.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.75.tar.tz > output-75.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.76.tar.tz > output-76.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.77.tar.tz > output-77.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.78.tar.tz > output-78.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.79.tar.tz > output-79.txt 2>&1 &
