
# น่าจะเสร็จแล้ว ต้องเช็ก
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.00.tar.gz > output-00.txt 2>&1 &

# กำลังรันอยู่
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.01.tar.gz > output-01.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.02.tar.gz > output-02.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.03.tar.gz > output-03.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.04.tar.gz > output-04.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.05.tar.gz > output-05.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.06.tar.gz > output-06.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.07.tar.gz > output-07.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.08.tar.gz > output-08.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.09.tar.gz > output-09.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.10.tar.gz > output-10.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.11.tar.gz > output-11.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.12.tar.gz > output-12.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.13.tar.gz > output-13.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.14.tar.gz > output-14.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.15.tar.gz > output-15.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.16.tar.gz > output-16.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.17.tar.gz > output-17.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.18.tar.gz > output-18.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.19.tar.gz > output-19.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.20.tar.gz > output-20.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.21.tar.gz > output-21.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.22.tar.gz > output-22.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.23.tar.gz > output-23.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.24.tar.gz > output-24.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.25.tar.gz > output-25.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.26.tar.gz > output-26.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.27.tar.gz > output-27.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.28.tar.gz > output-28.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.29.tar.gz > output-29.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.30.tar.gz > output-30.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.31.tar.gz > output-31.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.32.tar.gz > output-32.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.33.tar.gz > output-33.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.34.tar.gz > output-34.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.35.tar.gz > output-35.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.36.tar.gz > output-36.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.37.tar.gz > output-37.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.38.tar.gz > output-38.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.39.tar.gz > output-39.txt 2>&1 &


# ส่วนที่เหลือ
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.40.tar.gz > output-40.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.41.tar.gz > output-41.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.42.tar.gz > output-42.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.43.tar.gz > output-43.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.44.tar.gz > output-44.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.45.tar.gz > output-45.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.46.tar.gz > output-46.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.47.tar.gz > output-47.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.48.tar.gz > output-48.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.49.tar.gz > output-49.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.50.tar.gz > output-50.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.51.tar.gz > output-51.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.52.tar.gz > output-52.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.53.tar.gz > output-53.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.54.tar.gz > output-54.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.55.tar.gz > output-55.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.56.tar.gz > output-56.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.57.tar.gz > output-57.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.58.tar.gz > output-58.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.59.tar.gz > output-59.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.60.tar.gz > output-60.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.61.tar.gz > output-61.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.62.tar.gz > output-62.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.63.tar.gz > output-63.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.64.tar.gz > output-64.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.65.tar.gz > output-65.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.66.tar.gz > output-66.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.67.tar.gz > output-67.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.68.tar.gz > output-68.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.69.tar.gz > output-69.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.70.tar.gz > output-70.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.71.tar.gz > output-71.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.72.tar.gz > output-72.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.73.tar.gz > output-73.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.74.tar.gz > output-74.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.75.tar.gz > output-75.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.76.tar.gz > output-76.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.77.tar.gz > output-77.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.78.tar.gz > output-78.txt 2>&1 &
nohup wget https://ftp.ncbi.nlm.nih.gov/blast/db/nr.79.tar.gz > output-79.txt 2>&1 &
