#!/bin/bash
#SBATCH -p memory
#SBATCH -N 1 -c 96
#SBATCH -t 5-00:00:00
#SBATCH -J BWAjob
#SBATCH -A proj5034

module purge
module load SAMtools/1.9-intel-2019b

MAP_DIRECTORY="/tarafs/data/home/hrasoara/proj5034-AGBKU/map_bwa_ema_Ryan/sorted_final_bam"

genomes=(
    "EMAf10_q20_sorted.bam"
    "EMAf10_q20_sorted.bam.bai"
    "EMAf1_q20_sorted.bam"
    "EMAf28_q20_sorted.bam"
    "EMAf2_q20_sorted.bam"
    "EMAf3_q20_sorted.bam"
    "EMAf4_q20_sorted.bam"
    "EMAf5_q20_sorted.bam"
    "EMAf7_q20_sorted.bam"
    "EMAFf20_q20_sorted.bam"
    "EMAFf21_q20_sorted.bam"
    "EMAFf2_q20_sorted.bam"
    "EMAFf5_q20_sorted.bam"
    "EMAFf6_q20_sorted.bam"
    "EMAFm2_q20_sorted.bam"
    "EMAFm6_q20_sorted.bam"
    "EMAFm9_q20_sorted.bam"
    "EMAm10_q20_sorted.bam"
    "EMAm12_q20_sorted.bam"
    "EMAm13_q20_sorted.bam"
    "EMAm14_q20_sorted.bam"
    "EMAm16_q20_sorted.bam"
    "EMAm17_q20_sorted.bam"
    "EMAm18_q20_sorted.bam"
    "EMAm19_q20_sorted.bam"
    "EMAm1_q20_sorted.bam"
    "EMAm20_q20_sorted.bam"
    "EMAm2_q20_sorted.bam"
    "EMAm3_q20_sorted.bam"
    "EMAm5_q20_sorted.bam"
    "EMAm6_q20_sorted.bam"
    "EMAm7_q20_sorted.bam"
    "EMAm8_q20_sorted.bam"
    "EMAm9_q20_sorted.bam"
)
for genome in "${genomes[@]}"
do
    echo samtools index -@ 96 -b \
        "${MAP_DIRECTORY}/${genome}_q20.bam"
done